{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  labels:
    app: {{ .Release.Name }}
    {{- if .Values.labels.platform }}
    platform: {{ title .Values.labels.platform }}
    {{- end }}
{{- end }}