apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-clusterrole
  labels:
    chart: {{ .Chart.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'