apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    chart: {{ .Chart.Name }}
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy: {}
  template:
    metadata:
      labels:
        chart: {{ .Chart.Name }}
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image:  {{ .Values.deploy.image.repository }}:{{ .Values.deploy.image.tag }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "32Mi"
              cpu: "125m"
            limits:
              memory: "64Mi"
              cpu: "250m"
          env:
            - name: INFO_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INFO_POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: INFO_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INFO_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: INFO_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: INFO_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: INFO_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          volumeMounts:
            - name: podinfo
              mountPath: /etc/pod/labels
              readOnly: false
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels