apiVersion: v1
kind: Service
metadata:
  labels:
    chart: {{ .Chart.Name }}
  name: {{ .Release.Name }}-service
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}